CREATE TABLE IF NOT EXISTS recalls (
  id INTEGER PRIMARY KEY,
  rappel_guid TEXT NOT NULL,
  numero_fiche TEXT,
  numero_version INTEGER,
  nature_juridique_rappel TEXT,
  categorie_produit TEXT,
  sous_categorie_produit TEXT,
  marque_produit TEXT,
  modeles_ou_references TEXT,
  identification_produits TEXT,
  conditionnements TEXT,
  date_debut_commercialisation TEXT,
  date_date_fin_commercialisation TEXT,
  date_limite_de_consommation TEXT,
  temperature_conservation TEXT,
  marque_salubrite TEXT,
  informations_complementaires TEXT,
  zone_geographique_de_vente TEXT,
  distributeurs TEXT,
  motif_rappel TEXT,
  risques_encourus TEXT,
  preconisations_sanitaires TEXT,
  description_complementaire_risque TEXT,
  conduites_a_tenir_par_le_consommateur TEXT,
  numero_contact TEXT,
  modalites_de_compensation TEXT,
  date_de_fin_de_la_procedure_de_rappel TEXT,
  informations_complementaires_publiques TEXT,
  liens_vers_les_images TEXT,
  lien_vers_la_liste_des_produits TEXT,
  lien_vers_la_liste_des_distributeurs TEXT,
  lien_vers_affichette_pdf TEXT,
  lien_vers_la_fiche_rappel TEXT,
  date_publication TIMESTAMPTZ,
  libelle TEXT,
  updated_at TIMESTAMP DEFAULT now()
);
